export enum UserTheme {
  BLUE = 'blue',
  SKY = 'sky',
  INDIGO = 'indigo',
  AZURE = 'azure',
  TEAL = 'teal',
  EMERALD = 'emerald',
  MINT = 'mint',
  FOREST = 'forest',
  PINK = 'pink',
  BLUSH = 'blush',
  PEACH = 'peach',
  LAVENDER = 'lavender',
  ROSE = 'rose',
  CORAL = 'coral',
  AMBER = 'amber',
  WINE = 'wine',
  SLATE = 'slate',
  ZINC = 'zinc',
  STONE = 'stone',
  CHARCOAL = 'charcoal',
  /** Legacy — still accepted from older clients */
  FUCHSIA = 'fuchsia',
  PLUM = 'plum',
}
