export enum EntityType {
  PROPERTY = 'PROPERTY',
  TENANT = 'TENANT',
  LEASE = 'LEASE',
  DEMAND = 'DEMAND',
  PAYMENT = 'PAYMENT',
  DOCUMENT = 'DOCUMENT',
  NOTIFICATION = 'NOTIFICATION',
  MAINTENANCE = 'MAINTENANCE',
  USER = 'USER',
  ALLOCATION = 'ALLOCATION',
  PROPERTY_MANAGER = 'PROPERTY_MANAGER',
}
