export enum ReferenceType {
  // Tenant KYC
  PAN_DOCUMENT = 'PAN_DOCUMENT',
  AADHAAR_DOCUMENT = 'AADHAAR_DOCUMENT',
  GST_CERTIFICATE = 'GST_CERTIFICATE',
  ID_PROOF = 'ID_PROOF',

  // Lease
  LEASE_AGREEMENT = 'LEASE_AGREEMENT',
  POSSESSION_CERTIFICATE = 'POSSESSION_CERTIFICATE',
  LEASE_AMENDMENT = 'LEASE_AMENDMENT',

  // Property / site
  LAYOUT_IMAGE = 'LAYOUT_IMAGE',
  SITE_PLAN = 'SITE_PLAN',
  DIMENSIONAL_REPORT = 'DIMENSIONAL_REPORT',
  NOC = 'NOC',

  // Billing / tax
  TAX_RECEIPT = 'TAX_RECEIPT',
  TAX_INVOICE = 'TAX_INVOICE',
  CHALLAN = 'CHALLAN',
  PAYMENT_RECEIPT = 'PAYMENT_RECEIPT',

  // Compliance / legal
  LEGAL_NOTICE = 'LEGAL_NOTICE',
  COMPLIANCE_CERTIFICATE = 'COMPLIANCE_CERTIFICATE',
  COMPLIANCE_ARTEFACT = 'COMPLIANCE_ARTEFACT',

  // Notifications
  NOTIFICATION_ATTACHMENT = 'NOTIFICATION_ATTACHMENT',
  NOTIFICATION_REFERENCE_DOCUMENT = 'NOTIFICATION_REFERENCE_DOCUMENT',

  // Maintenance
  INSPECTION_REPORT = 'INSPECTION_REPORT',
  COMPLAINT_ATTACHMENT = 'COMPLAINT_ATTACHMENT',

  // Property Manager (Facility Manager)
  PROPERTY_MANAGER_PHOTO = 'PROPERTY_MANAGER_PHOTO',
  PROPERTY_MANAGER_OTHER_DOCUMENT = 'PROPERTY_MANAGER_OTHER_DOCUMENT',

  // Generic
  OTHER = 'OTHER',
}
